
x-common-config:
  &common-config
  image: apache/hadoop:3.4.1
  restart: unless-stopped
  volumes:
    - ./data:/data
  env_file:
    - ./hadoop.env

services:

  namenode:
    <<: *common-config
    hostname: namenode
    command: ["hdfs", "namenode"]
    ports:
      - 9870:9870
    environment:
      ENSURE_NAMENODE_DIR: "/data/dfs/name"
      HDFS-SITE.XML_dfs.namenode.name.dir: "/data/dfs/name"

  datanode:
    <<: *common-config
    command: ["hdfs", "datanode"]
    environment:
      HDFS-SITE.XML_dfs.datanode.data.dir: "/data/dfs/data"

  resourcemanager:
    <<: *common-config
    hostname: resourcemanager
    command: ["yarn", "resourcemanager"]
    ports:
      - 8088:8088

  nodemanager:
    <<: *common-config
    command: ["yarn", "nodemanager"]

  postgres:
    image: postgres:16.5
    restart: unless-stopped
    hostname: postgres
    environment:
      POSTGRES_DB: 'metastore_db'
      POSTGRES_USER: 'hive'
      POSTGRES_PASSWORD: 'password'
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgresql:/var/lib/postgresql

  metastore:
    image: apache/hive:4.0.1
    depends_on:
      - postgres
    restart: unless-stopped
    hostname: metastore
    environment:
      DB_DRIVER: postgres
      SERVICE_NAME: 'metastore'
      SERVICE_OPTS: '-Xmx1G -Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver
                     -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://postgres:5432/metastore_db
                     -Djavax.jdo.option.ConnectionUserName=hive
                     -Djavax.jdo.option.ConnectionPassword=password'
      HIVE_CUSTOM_CONF_DIR: /config/hive
    ports:
        - '9083:9083'
    volumes:
        - ./data/hive/warehouse:/opt/hive/data/warehouse
        - ./config/hive:/config/hive
        - type: bind
          source: ./jdbc/postgresql-42.7.2.jar
          target: /opt/hive/lib/postgresql-42.7.2.jar

  hiveserver2:
    image: apache/hive:4.0.1
    depends_on:
      - metastore
    restart: unless-stopped
    environment:
      HIVE_SERVER2_THRIFT_PORT: 10000
      SERVICE_OPTS: '-Xmx1G -Dhive.metastore.uris=thrift://metastore:9083'
      IS_RESUME: 'true'
      SERVICE_NAME: 'hiveserver2'
    ports:
      - '10000:10000'
      - '10002:10002'
    volumes:
      - ./data/hive/warehouse:/opt/hive/data/warehouse
